apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oz9n20yz3-python
  janus-idp.io/tekton: oz9n20yz3-python
  backstage.io/kubernetes-id: oz9n20yz3-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oz9n20yz3-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
